# .coderabbit.yaml
# Enable or disable features
features:
  summary: true              # Generate a summary of the pull request
  walkthrough: true          # Provide a walkthrough of the changes
  line_by_line_comments: true  # Enable line-by-line code review comments

# Language preferences
languages:
  - python
  - javascript
  - typescript
  - go

# Custom commands that can be triggered in PR comments
commands:
  generate-docstrings: true
  suggest-optimizations: true
  check-security: true

# Review behavior
review:
  on_open: true              # Trigger review when PR is opened
  on_update: true            # Trigger review when PR is updated (new commits)
  on_comment: true           # Trigger review when a comment is made
  review_status: true        # Enable review status messages
  incremental_review: true   # Review only new changes in subsequent commits
  auto_review_branches:      # Specify branches to auto-review (empty or '*' for all)
    - '*'                    # Review PRs targeting any branch

# Optional: Exclude specific files or directories from review
exclude:
  - "docs/"
  - "*.md"
